name: Créer Q3_archive_java.txt

on: [push]

permissions:
  contents: write

jobs:
  create-and-push-archive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Création du fichier Q3_archive_java.txt
        run: |
          echo "Boudeele Thomas" > Q3_archive_java.txt
          cat java/Q3.java >> Q3_archive_java.txt
          
      - name: Commit et push
        run: |
          git config --global user.name timberlek78
          git config --global user.email thomasboudeele1@gmail.com
          git add Q3_archive_java.txt
          git commit -m "Ajout de Q3_archive_java.txt"
          git push
